version: '3.2'

services:
  ipld-eth-db-v2:
    restart: always
    image: vulcanize/ipld-eth-db:v2.0.0
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_testing_v2"
      POSTGRES_PASSWORD: "password"
    volumes:
      - geth_node:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  ipld-eth-db-v3:
    restart: always
    image: vulcanize/ipld-eth-db:v3.0.6
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_testing_v3"
      POSTGRES_PASSWORD: "password"
    volumes:
      - geth_node:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  geth_node:
