version: "3.2"

services:
  ipld-eth-db:
    restart: on-failure
    depends_on:
      - access-node
    image: vulcanize/ipld-eth-db:v4.1.1-alpha
    environment:
      DATABASE_USER: "vdbm"
      DATABASE_NAME: "vulcanize_testing_v4"
      DATABASE_PASSWORD: "password"
      DATABASE_HOSTNAME: "access-node"
      DATABASE_PORT: 5432
