name: checks

on: [pull_request]

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          check-latest: true
      - uses: actions/checkout@v2
      - name: Run linter
        run: go run build/ci.go lint
